// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: pkg/grpc_db/grpc_db.proto

package SensorServer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *ConnReq) Reset() {
	*x = ConnReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_db_grpc_db_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnReq) ProtoMessage() {}

func (x *ConnReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_db_grpc_db_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnReq.ProtoReflect.Descriptor instead.
func (*ConnReq) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_db_grpc_db_proto_rawDescGZIP(), []int{0}
}

func (x *ConnReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ConnReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type DisConnReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DisConnReq) Reset() {
	*x = DisConnReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_db_grpc_db_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisConnReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisConnReq) ProtoMessage() {}

func (x *DisConnReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_db_grpc_db_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisConnReq.ProtoReflect.Descriptor instead.
func (*DisConnReq) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_db_grpc_db_proto_rawDescGZIP(), []int{1}
}

//used for both connect and disconnect
type ConnRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res string `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *ConnRes) Reset() {
	*x = ConnRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_db_grpc_db_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnRes) ProtoMessage() {}

func (x *ConnRes) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_db_grpc_db_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnRes.ProtoReflect.Descriptor instead.
func (*ConnRes) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_db_grpc_db_proto_rawDescGZIP(), []int{2}
}

func (x *ConnRes) GetRes() string {
	if x != nil {
		return x.Res
	}
	return ""
}

type InfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SensorName string `protobuf:"bytes,1,opt,name=sensorName,proto3" json:"sensorName,omitempty"`
	DayBefore  int32  `protobuf:"varint,2,opt,name=dayBefore,proto3" json:"dayBefore,omitempty"`
}

func (x *InfoReq) Reset() {
	*x = InfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_db_grpc_db_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoReq) ProtoMessage() {}

func (x *InfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_db_grpc_db_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoReq.ProtoReflect.Descriptor instead.
func (*InfoReq) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_db_grpc_db_proto_rawDescGZIP(), []int{3}
}

func (x *InfoReq) GetSensorName() string {
	if x != nil {
		return x.SensorName
	}
	return ""
}

func (x *InfoReq)GetDayBefore() int32 {
	if x != nil {
		return x.DayBefore
	}
	return 0
}

type InfoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Responce string `protobuf:"bytes,1,opt,name=responce,proto3" json:"responce,omitempty"`
}

func (x *InfoRes) Reset() {
	*x = InfoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_db_grpc_db_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRes) ProtoMessage() {}

func (x *InfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_db_grpc_db_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRes.ProtoReflect.Descriptor instead.
func (*InfoRes) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_db_grpc_db_proto_rawDescGZIP(), []int{4}
}

func (x *InfoRes) GetResponce() string {
	if x != nil {
		return x.Responce
	}
	return ""
}

type ConnSensorReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConnSensorReq) Reset() {
	*x = ConnSensorReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_db_grpc_db_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnSensorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnSensorReq) ProtoMessage() {}

func (x *ConnSensorReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_db_grpc_db_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnSensorReq.ProtoReflect.Descriptor instead.
func (*ConnSensorReq) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_db_grpc_db_proto_rawDescGZIP(), []int{5}
}

type ConnSensorRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Serial string `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
}

func (x *ConnSensorRes) Reset() {
	*x = ConnSensorRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_db_grpc_db_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnSensorRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnSensorRes) ProtoMessage() {}

func (x *ConnSensorRes) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_db_grpc_db_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnSensorRes.ProtoReflect.Descriptor instead.
func (*ConnSensorRes) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_db_grpc_db_proto_rawDescGZIP(), []int{6}
}

func (x *ConnSensorRes) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

type Measure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	M      int32  `protobuf:"varint,1,opt,name=m,proto3" json:"m,omitempty"`
	Serial string `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
}

func (x *Measure) Reset() {
	*x = Measure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_db_grpc_db_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Measure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Measure) ProtoMessage() {}

func (x *Measure) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_db_grpc_db_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Measure.ProtoReflect.Descriptor instead.
func (*Measure) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_db_grpc_db_proto_rawDescGZIP(), []int{7}
}

func (x *Measure) GetM() int32 {
	if x != nil {
		return x.M
	}
	return 0
}

func (x *Measure) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

type MeasureRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MeasureRes) Reset() {
	*x = MeasureRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_db_grpc_db_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeasureRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasureRes) ProtoMessage() {}

func (x *MeasureRes) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_db_grpc_db_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasureRes.ProtoReflect.Descriptor instead.
func (*MeasureRes) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_db_grpc_db_proto_rawDescGZIP(), []int{8}
}

var File_pkg_grpc_db_grpc_db_proto protoreflect.FileDescriptor

var file_pkg_grpc_db_grpc_db_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x64, 0x62, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x5f, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x53, 0x65, 0x6e,
	0x73, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x41, 0x0a, 0x07, 0x43, 0x6f, 0x6e,
	0x6e, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x0c, 0x0a, 0x0a,
	0x44, 0x69, 0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x65, 0x71, 0x22, 0x1b, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x47, 0x0a, 0x07, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x61, 0x79, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x64, 0x61, 0x79, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65,
	0x22, 0x25, 0x0a, 0x07, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x22, 0x0f, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x6e, 0x53,
	0x65, 0x6e, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x22, 0x27, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x6e,
	0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72,
	0x69, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x22, 0x2f, 0x0a, 0x07, 0x6d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x12, 0x0c, 0x0a, 0x01,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x22, 0x0c, 0x0a, 0x0a, 0x6d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73,
	0x32, 0xcf, 0x01, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x3f, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x12, 0x15, 0x2e, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x65, 0x73, 0x22, 0x00,
	0x12, 0x39, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x15, 0x2e, 0x53, 0x65,
	0x6e, 0x73, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x1a, 0x15, 0x2e, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x10, 0x44,
	0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12,
	0x18, 0x2e, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x44,
	0x69, 0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x53, 0x65, 0x6e, 0x73,
	0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x65, 0x73,
	0x22, 0x00, 0x32, 0x9f, 0x01, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x12, 0x4b, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x53, 0x65,
	0x6e, 0x73, 0x6f, 0x72, 0x12, 0x1b, 0x2e, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x52, 0x65,
	0x71, 0x1a, 0x1b, 0x2e, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x22, 0x00,
	0x12, 0x42, 0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72,
	0x65, 0x12, 0x15, 0x2e, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x6d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x1a, 0x18, 0x2e, 0x53, 0x65, 0x6e, 0x73, 0x6f,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x6d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x52,
	0x65, 0x73, 0x22, 0x00, 0x42, 0x2f, 0x5a, 0x2d, 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x6e,
	0x6f, 0x61, 0x6d, 0x77, 0x65, 0x69, 0x6c, 0x65, 0x72, 0x2f, 0x47, 0x6f, 0x6c, 0x61, 0x6e, 0x64,
	0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2f, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_grpc_db_grpc_db_proto_rawDescOnce sync.Once
	file_pkg_grpc_db_grpc_db_proto_rawDescData = file_pkg_grpc_db_grpc_db_proto_rawDesc
)

func file_pkg_grpc_db_grpc_db_proto_rawDescGZIP() []byte {
	file_pkg_grpc_db_grpc_db_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_db_grpc_db_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_grpc_db_grpc_db_proto_rawDescData)
	})
	return file_pkg_grpc_db_grpc_db_proto_rawDescData
}

var file_pkg_grpc_db_grpc_db_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_grpc_db_grpc_db_proto_goTypes = []interface{}{
	(*ConnReq)(nil),       // 0: SensorServer.ConnReq
	(*DisConnReq)(nil),    // 1: SensorServer.DisConnReq
	(*ConnRes)(nil),       // 2: SensorServer.ConnRes
	(*InfoReq)(nil),       // 3: SensorServer.InfoReq
	(*InfoRes)(nil),       // 4: SensorServer.InfoRes
	(*ConnSensorReq)(nil), // 5: SensorServer.ConnSensorReq
	(*ConnSensorRes)(nil), // 6: SensorServer.ConnSensorRes
	(*Measure)(nil),       // 7: SensorServer.measure
	(*MeasureRes)(nil),    // 8: SensorServer.measureRes
}
var file_pkg_grpc_db_grpc_db_proto_depIdxs = []int32{
	0, // 0: SensorServer.ClientInfo.ConnectClient:input_type -> SensorServer.ConnReq
	3, // 1: SensorServer.ClientInfo.GetInfo:input_type -> SensorServer.InfoReq
	1, // 2: SensorServer.ClientInfo.DisconnectClient:input_type -> SensorServer.DisConnReq
	5, // 3: SensorServer.SensorStream.ConnectSensor:input_type -> SensorServer.ConnSensorReq
	7, // 4: SensorServer.SensorStream.SensorMeasure:input_type -> SensorServer.measure
	2, // 5: SensorServer.ClientInfo.ConnectClient:output_type -> SensorServer.ConnRes
	4, // 6: SensorServer.ClientInfo.GetInfo:output_type -> SensorServer.InfoRes
	2, // 7: SensorServer.ClientInfo.DisconnectClient:output_type -> SensorServer.ConnRes
	6, // 8: SensorServer.SensorStream.ConnectSensor:output_type -> SensorServer.ConnSensorRes
	8, // 9: SensorServer.SensorStream.SensorMeasure:output_type -> SensorServer.measureRes
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_grpc_db_grpc_db_proto_init() }
func file_pkg_grpc_db_grpc_db_proto_init() {
	if File_pkg_grpc_db_grpc_db_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_grpc_db_grpc_db_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_db_grpc_db_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisConnReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_db_grpc_db_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_db_grpc_db_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_db_grpc_db_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_db_grpc_db_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnSensorReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_db_grpc_db_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnSensorRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_db_grpc_db_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Measure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_db_grpc_db_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeasureRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_grpc_db_grpc_db_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_grpc_db_grpc_db_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_db_grpc_db_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_db_grpc_db_proto_msgTypes,
	}.Build()
	File_pkg_grpc_db_grpc_db_proto = out.File
	file_pkg_grpc_db_grpc_db_proto_rawDesc = nil
	file_pkg_grpc_db_grpc_db_proto_goTypes = nil
	file_pkg_grpc_db_grpc_db_proto_depIdxs = nil
}
